### ISSUE TITLE
https mixed content

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus-maven-plugin#70]
firefox and chrome say that there is http:// images queried on the website, but I also couldn't find specifics.  might be this: 
```
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M19 6.734c0 4.164-3.75 6.98-3.75 10.266h-6.5c0-3.286-3.75-6.103-3.75-10.266 0-4.343 3.498-6.734 6.996-6.734 3.502 0 7.004 2.394 7.004 6.734zm-4.5 11.266h-5c-.276 0-.5.224-.5.5s.224.5.5.5h5c.276 0 .5-.224.5-.5s-.224-.5-.5-.5zm0 2h-5c-.276 0-.5.224-.5.5s.224.5.5.5h5c.276 0 .5-.224.5-.5s-.224-.5-.5-.5zm.25 2h-5.5l1.451 1.659c.19.216.465.341.753.341h1.093c.288 0 .562-.125.752-.341l1.451-1.659z"/></svg>
```

![Screenshot from 2019-05-16 12-00-12](https://user-images.githubusercontent.com/900758/57845389-3787e080-77d2-11e9-9f1c-3e07300d0af9.png)

**Comment by JJ-Author** [comment]
Mixed Content: The page at 'https://databus.dbpedia.org/' was loaded over HTTPS, but requested an insecure image 'http://www.w3.org/RDF/icons/rdf_flyer.24'. This content should also be served over HTTPS.
(index):1 Mixed Content: The page at 'https://databus.dbpedia.org/' was loaded over HTTPS, but requested an insecure favicon 'http://databus.dbpedia.org/images/favicon.png?auth_callback=1&error=login_required&state=813f3ea8-4d3e-455f-9c94-8ff4c8b1425b'. This request has been blocked; the content must be served over HTTPS.

**Comment by kurzum** [comment]
Ok, cool. What tool did you use to display this? 

On May 16, 2019 3:55:31 PM GMT+02:00, JJ-Author <notifications@github.com> wrote:
>Mixed Content: The page at 'https://databus.dbpedia.org/' was loaded
>over HTTPS, but requested an insecure image
>'http://www.w3.org/RDF/icons/rdf_flyer.24'. This content should also be
>served over HTTPS.
>(index):1 Mixed Content: The page at 'https://databus.dbpedia.org/' was
>loaded over HTTPS, but requested an insecure favicon
>'http://databus.dbpedia.org/images/favicon.png?auth_callback=1&error=login_required&state=813f3ea8-4d3e-455f-9c94-8ff4c8b1425b'.
>This request has been blocked; the content must be served over HTTPS.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dbpedia/databus-maven-plugin/issues/70#issuecomment-493077781

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by holycrab13** [comment]
This is caused by the RDF logo in the header, fill fix asap

**Comment by JJ-Author** [comment]
> Ok, cool. What tool did you use to display this?
> […](#)
> On May 16, 2019 3:55:31 PM GMT+02:00, JJ-Author ***@***.***> wrote: Mixed Content: The page at 'https://databus.dbpedia.org/' was loaded over HTTPS, but requested an insecure image 'http://www.w3.org/RDF/icons/rdf_flyer.24'. This content should also be served over HTTPS. (index):1 Mixed Content: The page at 'https://databus.dbpedia.org/' was loaded over HTTPS, but requested an insecure favicon 'http://databus.dbpedia.org/images/favicon.png?auth_callback=1&error=login_required&state=813f3ea8-4d3e-455f-9c94-8ff4c8b1425b'. This request has been blocked; the content must be served over HTTPS. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#70 (comment)](https://github.com/dbpedia/databus-maven-plugin/issues/70#issuecomment-493077781)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

chrome builtin developer tools under network tab

**Comment by holycrab13** [comment]
Fixed, saved the icon causing the warning to the local images

**Comment by JJ-Author** [comment]
No not fixed

Mixed Content: The page at 'https://databus.dbpedia.org/' was loaded over HTTPS, but requested an insecure favicon 'http://databus.dbpedia.org/images/favicon.png?auth_callback=1&error=login_required&state=56b710db-2f31-4a14-877b-ef1094ebb148'. This request has been blocked; the content must be served over HTTPS.

**Comment by holycrab13** [comment]
Also fixed for the favicon

**Comment by holycrab13** [comment]
Also fixed for the favicon
